"use client";
import { 
  GlobeAltIcon, 
  SparklesIcon, 
  FireIcon, 
  HeartIcon, 
  ChatBubbleLeftRightIcon,
  PlayCircleIcon,
  MagnifyingGlassIcon,
  ChevronRightIcon
} from "@heroicons/react/24/outline";

export default function DiscoverPage() {
  const categories = ["Trending", "Cinematic", "Anime", "3D Render", "Abstract", "Photography"];
  
  // High-end placeholders for the "Discover" gallery
  const feedItems = [
    { id: 1, title: "Neon Cyberpunk Metropolis", author: "@obsidian_gen", likes: "2.4k", type: "Video", color: "#3b82f6" },
    { id: 2, title: "Surreal Desert Bloom", author: "@flux_master", likes: "1.8k", type: "Image", color: "#ec4899" },
    { id: 3, title: "Hyper-realistic Portrait", author: "@human_ai", likes: "3.2k", type: "Image", color: "#10b981" },
    { id: 4, title: "Fluid Motion Study", author: "@motion_pro", likes: "950", type: "Video", color: "#f59e0b" },
    { id: 5, title: "Ancient Ruins Reimagined", author: "@history_ai", likes: "1.2k", type: "Image", color: "#8b5cf6" },
    { id: 6, title: "Deep Space Voyager", author: "@cosmos_gen", likes: "4.5k", type: "Video", color: "#06b6d4" },
  ];

  return (
    <div className="p-8 space-y-10 max-w-[1600px] mx-auto h-full flex flex-col overflow-y-auto custom-scrollbar">
      {/* Header Section */}
      <div className="flex justify-between items-end border-b border-app-border pb-8">
        <div>
          <div className="flex items-center gap-2 mb-2">
             <GlobeAltIcon className="w-4 h-4 text-text-accent" />
             <span className="text-[10px] font-black uppercase tracking-[0.3em] text-text-accent">Community Engine</span>
          </div>
          <h1 className="text-4xl font-bold text-white tracking-tight">Discover</h1>
          <p className="text-text-muted text-sm font-medium mt-1">Explore the most innovative content generated by the MYG community.</p>
        </div>
        
        <div className="flex items-center gap-4">
          <div className="relative group">
            <MagnifyingGlassIcon className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-text-muted group-focus-within:text-white transition-colors" />
            <input 
              type="text" 
              placeholder="Search inspiration..." 
              className="bg-app-input border border-app-border rounded-editor py-2 pl-9 pr-4 text-[12px] text-white w-64 focus:border-text-accent/50 outline-none transition-all placeholder:text-text-muted/30"
            />
          </div>
          <button className="bg-white hover:bg-gray-200 text-black px-6 py-2.5 rounded-editor font-bold text-[11px] uppercase tracking-widest transition-premium shadow-glow flex items-center gap-2">
            <SparklesIcon className="w-4 h-4 stroke-[2.5]" /> Submit Yours
          </button>
        </div>
      </div>

      {/* Category Pills */}
      <div className="flex gap-3 overflow-x-auto hide-scrollbar pb-2">
        {categories.map((cat, i) => (
          <button 
            key={cat} 
            className={`px-5 py-2 rounded-full text-[11px] font-black uppercase tracking-widest transition-premium border ${
              i === 0 
                ? "bg-text-accent border-text-accent text-white shadow-glow" 
                : "bg-app-input border-app-border text-text-muted hover:text-white hover:border-text-muted"
            }`}
          >
            {cat}
          </button>
        ))}
      </div>

      {/* Main Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {feedItems.map((item) => (
          <div key={item.id} className="group relative bg-app-card border border-app-border rounded-editor overflow-hidden cursor-pointer hover:border-text-accent/30 transition-premium shadow-premium">
            {/* Visual Placeholder */}
            <div className="aspect-video bg-app-bg relative flex items-center justify-center overflow-hidden">
                {/* Decorative Gradient Background */}
                <div className="absolute inset-0 opacity-10 group-hover:opacity-20 transition-opacity" style={{ background: `radial-gradient(circle at center, ${item.color}, transparent)` }} />
                
                {item.type === "Video" ? (
                    <PlayCircleIcon className="w-12 h-12 text-white/20 group-hover:text-text-accent group-hover:scale-110 transition-all duration-500" />
                ) : (
                    <SparklesIcon className="w-12 h-12 text-white/20 group-hover:text-green-500 group-hover:scale-110 transition-all duration-500" />
                )}

                {/* Tag */}
                <div className="absolute top-4 left-4 px-2 py-1 bg-black/60 backdrop-blur-md border border-white/10 rounded text-[9px] font-black uppercase tracking-widest text-white">
                    {item.type}
                </div>
            </div>

            {/* Content Info */}
            <div className="p-5 space-y-4">
                <div className="flex justify-between items-start">
                    <div className="space-y-1">
                        <h3 className="text-[14px] font-bold text-white tracking-tight group-hover:text-text-accent transition-colors">{item.title}</h3>
                        <p className="text-[11px] text-text-muted font-medium">{item.author}</p>
                    </div>
                    <button className="p-2 hover:bg-app-hover rounded-editor text-text-muted hover:text-white transition-colors">
                        <HeartIcon className="w-4 h-4" />
                    </button>
                </div>

                <div className="flex items-center justify-between pt-4 border-t border-white/[0.03]">
                    <div className="flex gap-4">
                        <div className="flex items-center gap-1.5">
                            <FireIcon className="w-3.5 h-3.5 text-orange-500" />
                            <span className="text-[10px] font-bold text-text-muted">{item.likes}</span>
                        </div>
                        <div className="flex items-center gap-1.5">
                            <ChatBubbleLeftRightIcon className="w-3.5 h-3.5 text-text-muted" />
                            <span className="text-[10px] font-bold text-text-muted">42</span>
                        </div>
                    </div>
                    <button className="text-[10px] font-black uppercase tracking-widest text-text-muted hover:text-white flex items-center gap-1 group/btn">
                        View Details <ChevronRightIcon className="w-3 h-3 group-hover/btn:translate-x-1 transition-transform" />
                    </button>
                </div>
            </div>

            {/* Hover Shine Effect */}
            <div className="absolute inset-0 bg-gradient-to-tr from-white/[0.02] to-transparent opacity-0 group-hover:opacity-100 pointer-events-none transition-opacity" />
          </div>
        ))}
      </div>

      {/* Footer / Load More */}
      <div className="flex justify-center py-10">
         <button className="px-8 py-3 bg-app-card border border-app-border rounded-editor text-[11px] font-black uppercase tracking-widest text-text-muted hover:text-white hover:border-text-muted transition-premium">
            Load More Creations
         </button>
      </div>
    </div>
  );
}